SOPA: programa.o	
	gcc -o programa.o

programa.o: programa.c
	gcc -c programa.c

SOPA2: programa_MEJORADO.o	
	gcc -o programa_MEJORADO.o

programa2.o: programa_MEJORADO.c
	gcc -c programa_MEJORADO.c
